"""alter table

Revision ID: 2343cb1eb42d
Revises: 91e65f0b993d
Create Date: 2024-01-26 22:16:16.278761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2343cb1eb42d'
down_revision: Union[str, None] = '91e65f0b993d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cities', 'region',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('cities', 'municipality',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('cities', 'settlement',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.alter_column('cities', 'oktmo',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('cities', 'birth',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.DECIMAL(precision=5, scale=1),
               existing_nullable=True)
    op.alter_column('cities', 'death',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.DECIMAL(precision=5, scale=1),
               existing_nullable=True)
    op.alter_column('cities', 'doctors_per10',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               type_=sa.DECIMAL(precision=5, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cities', 'doctors_per10',
               existing_type=sa.DECIMAL(precision=5, scale=1),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=True)
    op.alter_column('cities', 'death',
               existing_type=sa.DECIMAL(precision=5, scale=1),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=True)
    op.alter_column('cities', 'birth',
               existing_type=sa.DECIMAL(precision=5, scale=1),
               type_=sa.NUMERIC(precision=3, scale=1),
               existing_nullable=True)
    op.alter_column('cities', 'oktmo',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('cities', 'settlement',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('cities', 'municipality',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.alter_column('cities', 'region',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###
