"""initial

Revision ID: 91e65f0b993d
Revises: 
Create Date: 2024-01-26 01:59:31.215005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91e65f0b993d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=256), nullable=True),
    sa.Column('municipality', sa.String(length=256), nullable=True),
    sa.Column('settlement', sa.String(length=256), nullable=True),
    sa.Column('oktmo', sa.String(length=32), nullable=True),
    sa.Column('latitude_dd', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('longitude_dd', sa.DECIMAL(precision=15, scale=2), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('birth', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('crimes', sa.Integer(), nullable=True),
    sa.Column('death', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('doctors', sa.Integer(), nullable=True),
    sa.Column('doctors_per10', sa.DECIMAL(precision=3, scale=1), nullable=True),
    sa.Column('hospitals', sa.Integer(), nullable=True),
    sa.Column('job_regist', sa.Integer(), nullable=True),
    sa.Column('n_companies', sa.Integer(), nullable=True),
    sa.Column('pens', sa.DECIMAL(precision=10, scale=1), nullable=True),
    sa.Column('pop_work', sa.DECIMAL(precision=10, scale=1), nullable=True),
    sa.Column('wage', sa.DECIMAL(precision=10, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_id'), 'cities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cities_id'), table_name='cities')
    op.drop_table('cities')
    # ### end Alembic commands ###
