"""alter hospitals

Revision ID: d12ed1f14e21
Revises: 0844871c4742
Create Date: 2024-01-26 22:20:19.731339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12ed1f14e21'
down_revision: Union[str, None] = '0844871c4742'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cities', 'job_regist',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(precision=6, scale=1),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cities', 'job_regist',
               existing_type=sa.DECIMAL(precision=6, scale=1),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
